server:
  port: 8000
spring:
  application:
    name: NosHome
  profiles:
    active: dev

logging.level:
  com.nos.home : debug
  org.springframework.web.servlet : debug
  org.hibernate.type.descriptor.sql.BasicBinder : trace
