spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/noshouse
    username: noshouse
    password: jh4527
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view : true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect